### ISSUE TITLE
atmosphere sensor overflow stuff

### ISSUE THREAD

**Issue by mtfurlan** [i3detroit/custom-mqtt-programs#13]

**Comment by mkfink** [comment]
Overflowing:
tele/i3/inside/fablab/sensor-cluster/bmp280 {"Temperature":24.63, "Pressure":98997.10}
tele/i3/inside/fablab/sensor-cluster/lux {"Lux":0}
83647 {"Temperature":2147483647.2147483647, "Humidity":2147483647.2147483647}

**Comment by mkfink** [comment]
The office thermostat has the same overflow error.

![image](https://user-images.githubusercontent.com/11447986/35512221-ed9a5d1e-04cc-11e8-8004-54a0320495a9.png)

**Comment by mtfurlan** [comment]
Oh good. Does someone else want to look at my code because I'm apparently
incapable of dealing with pointers?

**Comment by mkfink** [comment]
atmosphere sensors haven't had any overflows since changing to bme280 sensors, but the office thermostat is still overflowing. Example:
`2018-02-03 16:37:45.241 tele/i3/inside/office/thermostat/bme280 {"Temperature":17.94, "Pressure":83647, "Humidity":2147483647.2147483647}`

**Comment by mtfurlan** [comment]
@mkfink Is the thermostat still having this issue?

**Comment by abzman** [comment]
@mkfink has this issue been solved?

**Comment by mkfink** [comment]
Yeah, it's been fixed since mark fixed the ftoa function we were using.
