### ISSUE TITLE
3 Thermostats heat only

### ISSUE THREAD

**Issue by mtfurlan** [i3detroit/custom-mqtt-programs#16]

**Comment by abzman** [comment]
boards being sent to fab

**Comment by mtfurlan** [comment]
Next version if it exists:
Mounting holes
Put ground plane on front instead of back

**Comment by abzman** [comment]
@mtfurlan need a flag for heat only (or cool only)
need to make sure we don't write to eeprom if no changes need to be made
@mkfink we need enclosures now
