### ISSUE TITLE
Thermostat only reports rounded temperature

### ISSUE THREAD

**Issue by mkfink** [i3detroit/custom-mqtt-programs#28]
When reporting the temperature measured by the bmp280 over mqtt, the value is almost always rounded to the nearest whole number but then with two decimals of precision. For example, it only reports 25.00, 25.00, ..., 26.00, ... etc.

![image](https://user-images.githubusercontent.com/11447986/35340491-48092d46-00f1-11e8-933a-1a95976a6d0f.png)

**Comment by mtfurlan** [comment]
Oh yeah cause evan only wanted to display whole numbers on the display and
then I used that for the reporting.

**Comment by mkfink** [comment]
It sometimes still reports out decimal fractions from halves to fifths, i.e 25.33, 24.80, etc. That suggests there might be something amiss. Will that cause any overflows?

**Comment by mtfurlan** [comment]
I'm seeing stuff like .4 and .62. I'm not worrying.
