### ISSUE TITLE
small bathroom fan

### ISSUE THREAD

**Issue by abzman** [i3detroit/custom-mqtt-programs#47]
parts in mail, needs laser-ed half cover though

**Comment by abzman** [comment]
hardware is in

**Comment by abzman** [comment]
flashed, need to install and add laser cut half-outlet cover

**Comment by mtfurlan** [comment]
TODO: .5 hour timeout in home assistant

**Comment by mkfink** [comment]
Done https://github.com/i3detroit/homeassistant-config/commit/5e462531737cb4c16d61df2356b16e571c54cd57
