### ISSUE TITLE
front door controller

### ISSUE THREAD

**Issue by mtfurlan** [i3detroit/custom-mqtt-programs#6]
reset emergency lights - Mark/Evan
needs analog voltage monitoring of the battery/power supply - Mark/Evan

**Comment by abzman** [comment]
maybe add reed switch for front door https://github.com/i3detroit/custom-mqtt-programs/issues/46

**Comment by abzman** [comment]
analog voltage reading added

**Comment by abzman** [comment]
added emergency lights power switch

**Comment by abzman** [comment]
all implemented, need to be tracked in homeassistant

**Comment by mtfurlan** [comment]
@mkfink This is done right?

**Comment by mkfink** [comment]
Yes. Reset emergency lights and warning for low voltage are implemented in home assistant
